language: php

php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6

matrix:
    include:
        - php: 5.3.3
          env: dependencies=lowest

before_install:
    - composer self-update
    - composer install -n

install:
    - [ "$dependencies" = "lowest" ] && composer update --prefer-lowest --prefer-stable -n

script:
    - echo '[phpspec] Running'; ./vendor/bin/phpspec run
    - echo '[phpunit] Running'; ./vendor/bin/phpunit
