language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
    - composer self-update

install:
    - composer install --dev --no-interaction --prefer-dist

script:
    - bin/phpspec run && bin/phpunit
